# Runbook for the OpenClaw gateway in Docker.
#
# Order for a bootstrap from scratch:
#   1. cp secrets.env.example secrets.env  and fill in the API key + the Telegram token
#   2. make setup             builds .env, fixes permissions, starts the gateway
#   3. make onboard           registers the LLM provider (headless, no prompts)
#   4. make telegram-pairing  connects the bot in pairing mode
#   5. message the bot; its reply contains your numeric user id
#   6. make lockdown ID=<your-user-id>   locks the bot to your account and only yours
#   7. make verify

SHELL := /bin/bash
.DEFAULT_GOAL := help

BASE := $(patsubst %/,%,$(dir $(abspath $(lastword $(MAKEFILE_LIST)))))
REPO := $(BASE)/repo

# Fixed project name. Without this Compose would derive it from the directory of the
# first -f (i.e. "repo") and the named volumes would change if files moved.
COMPOSE_PROJECT_NAME := openclaw-agent

# State paths, outside the container so they survive image replacement.
OPENCLAW_CONFIG_DIR := $(BASE)/state
OPENCLAW_WORKSPACE_DIR := $(BASE)/workspace
OPENCLAW_AUTH_PROFILE_SECRET_DIR := $(BASE)/auth-secrets

include config.env
export

# Lazy expansion (=, not :=): docker-compose.extra.yml is generated by setup.sh,
# so it may not exist yet when make parses this file.
EXTRA = $(wildcard $(REPO)/docker-compose.extra.yml)
COMPOSE = docker compose -f $(REPO)/docker-compose.yml \
	$(if $(EXTRA),-f $(EXTRA),) \
	-f $(BASE)/docker-compose.hardening.yml

# Runs a CLI subcommand in a one-shot container, without depending on the gateway
# being alive. -T avoids requesting a pseudo-TTY (there isn't one in automation).
ONESHOT = $(COMPOSE) run -T --rm --no-deps --entrypoint node openclaw-gateway dist/index.js

.PHONY: help
help:
	@echo "Bootstrap:  setup  onboard  telegram-pairing  lockdown ID=<userid>  verify"
	@echo "Operation:  up  down  restart  ps  logs  health  dashboard  doctor"
	@echo "Debugging:  cli CMD='...'  shell  config-get P=<path>  whoami-help"
	@echo "Upgrade:    update"

# ---------------------------------------------------------------- bootstrap

.PHONY: dirs
dirs:
	@mkdir -p $(OPENCLAW_CONFIG_DIR) $(OPENCLAW_WORKSPACE_DIR) $(OPENCLAW_AUTH_PROFILE_SECRET_DIR)
	@chmod 700 $(OPENCLAW_CONFIG_DIR) $(OPENCLAW_AUTH_PROFILE_SECRET_DIR)

.PHONY: sync-secrets
sync-secrets:
	@bash $(BASE)/bin/sync-secrets.sh

# setup.sh rewrites repo/.env from the environment on every run, generates
# docker-compose.extra.yml for the /home/node volume, fixes the uid on the bind
# mounts with a one-shot root container, and brings the gateway up.
# Interactive onboarding is disabled via OPENCLAW_SKIP_ONBOARDING in config.env.
.PHONY: setup
setup: dirs sync-secrets
	@bash $(REPO)/scripts/docker/setup.sh
	@$(MAKE) --no-print-directory fix-home-perms
	@$(MAKE) --no-print-directory up

# setup.sh's chown covers /home/node/.openclaw and /home/node/.config/openclaw,
# but not /home/node/.cache. In the -browser image that directory is created by
# root during the build (installing Playwright's Chromium), and the named volume
# copies that ownership verbatim. Result: the gateway runs as uid 1000, cannot
# create its temp directory /home/node/.cache/openclaw-1000, and enters a restart
# loop with "SQLite read-only worker Unable to create fallback temp dir".
#
# The contents of .cache (~1 GB of Chromium) are already node:node, so the chown
# deliberately omits -R: it fixes the directory without walking the whole tree.
.PHONY: fix-home-perms
fix-home-perms:
	@docker run --rm -v $(COMPOSE_PROJECT_NAME)_$(OPENCLAW_HOME_VOLUME):/home/node \
		--user 0:0 --entrypoint sh $(OPENCLAW_IMAGE) \
		-c 'chown node:node /home/node/.cache' 
	@echo "==> Permissions on /home/node/.cache fixed"

# Prompt-free onboarding. --secret-input-mode ref leaves the key as a reference to
# the environment variable instead of writing it inside openclaw.json.
.PHONY: onboard
onboard:
	$(ONESHOT) onboard --non-interactive --accept-risk --skip-health \
		--mode local \
		--auth-choice $(OPENCLAW_AUTH_CHOICE) \
		--secret-input-mode ref \
		--gateway-auth token \
		--gateway-token-ref-env OPENCLAW_GATEWAY_TOKEN \
		--skip-channels \
		--no-install-daemon
	@$(MAKE) --no-print-directory up

# Connects Telegram in pairing mode. --use-env keeps the token in the environment
# variable instead of copying it into openclaw.json, so TELEGRAM_BOT_TOKEN has to
# stay in repo/.env after this.
#
# pairing is a transient state: it exists to discover your numeric user id.
# Don't leave it like this, go through `make lockdown`.
.PHONY: telegram-pairing
telegram-pairing:
	$(ONESHOT) channels add --channel telegram --use-env
	$(ONESHOT) config set --batch-json '[{"path":"channels.telegram.dmPolicy","value":"pairing"}]'
	@$(MAKE) --no-print-directory up
	@echo ""
	@echo "Now send your bot a message on Telegram."
	@echo "It will reply with a pairing code and your numeric user id."
	@echo "Then:  make lockdown ID=<that-user-id>"

# Locks the bot down: only your user id can talk to it, and only you are owner of
# privileged commands and execution approvals.
#
# dmPolicy allowlist with an explicit allowFrom is the right setting for a
# single-owner bot. With "open" + allowFrom ["*"] anyone who guesses the bot's
# name would have shell access in this container.
.PHONY: lockdown
lockdown:
	@test -n "$(ID)" || { echo "ERROR: ID is missing. Usage: make lockdown ID=123456789"; exit 1; }
	@echo "$(ID)" | grep -Eq '^[0-9]+$$' || { echo "ERROR: ID must be your NUMERIC Telegram user id, not a username and not a group chat."; exit 1; }
	$(ONESHOT) config set --batch-json '[ \
		{"path":"channels.telegram.dmPolicy","value":"allowlist"}, \
		{"path":"channels.telegram.allowFrom","value":["$(ID)"]}, \
		{"path":"channels.telegram.groupPolicy","value":"allowlist"}, \
		{"path":"commands.ownerAllowFrom","value":["telegram:$(ID)"]} \
	]'
	@$(MAKE) --no-print-directory up
	@echo "==> Bot restricted to user id $(ID)"

# Web search backend for the web_search tool. No provider auto-selects itself
# without a usable credential, so it has to be chosen by hand.
#
# parallel-free: no API key, an index built for agents, returns dense extracts
# ordered for LLM context. The other key-free option is duckduckgo, but upstream
# flags it as experimental because it scrapes HTML without JS and breaks against
# anti-bot challenges. If you want country/language filters and more reliability,
# go with Brave: put BRAVE_API_KEY in secrets.env and set provider=brave.
.PHONY: websearch
websearch:
	@$(COMPOSE) run -T --rm openclaw-cli plugins install @openclaw/parallel-plugin || true
	@$(COMPOSE) run -T --rm openclaw-cli config set tools.web.search.provider parallel-free
	@$(MAKE) --no-print-directory up

.PHONY: verify
verify:
	@bash $(BASE)/bin/verify.sh

# ---------------------------------------------------------------- operation

.PHONY: up
up:
	@$(COMPOSE) up -d openclaw-gateway

.PHONY: down
down:
	@$(COMPOSE) down

# restart does NOT reload environment changes; up -d recreates the container and does.
.PHONY: restart
restart:
	@$(COMPOSE) up -d --force-recreate openclaw-gateway

.PHONY: ps
ps:
	@$(COMPOSE) ps

.PHONY: logs
logs:
	@$(COMPOSE) logs -f --tail 100 openclaw-gateway

.PHONY: health
health:
	@printf 'healthz  '; curl -fsS http://127.0.0.1:$(OPENCLAW_GATEWAY_PORT)/healthz  && echo || echo FAILED
	@printf 'startupz '; curl -fsS http://127.0.0.1:$(OPENCLAW_GATEWAY_PORT)/startupz && echo || echo FAILED
	@printf 'readyz   '; curl -fsS http://127.0.0.1:$(OPENCLAW_GATEWAY_PORT)/readyz   && echo || echo FAILED

.PHONY: dashboard
dashboard:
	@$(COMPOSE) run -T --rm openclaw-cli dashboard --no-open

.PHONY: doctor
doctor:
	@$(COMPOSE) run -T --rm openclaw-cli doctor --json

# ---------------------------------------------------------------- debugging

.PHONY: cli
cli:
	@test -n "$(CMD)" || { echo "Usage: make cli CMD='channels list'"; exit 1; }
	@$(COMPOSE) run -T --rm openclaw-cli $(CMD)

.PHONY: shell
shell:
	@$(COMPOSE) exec openclaw-gateway bash

.PHONY: config-get
config-get:
	@test -n "$(P)" || { echo "Usage: make config-get P=channels.telegram"; exit 1; }
	@$(COMPOSE) run -T --rm openclaw-cli config get $(P)

.PHONY: whoami-help
whoami-help:
	@echo "Your numeric Telegram user id, in order of preference:"
	@echo "  1. make telegram-pairing and read it in the bot's reply"
	@echo "  2. make logs and look for senderUserId in the 'telegram pairing request' entry"
	@echo "  3. once authorized, /whoami@<bot_name> in an allowed group"

# ---------------------------------------------------------------- upgrade

# Rolling tags (latest*) are rebuilt weekly with OS patches. Startup applies
# upgrade migrations on its own; if the gateway ends up in a restart loop, run
# `make doctor` against the same mounted state.
.PHONY: update
update:
	@docker pull $(OPENCLAW_IMAGE)
	@$(COMPOSE) up -d --force-recreate openclaw-gateway
	@$(MAKE) --no-print-directory health
